GET http://localhost:5000/

###

POST http://localhost:5000/register
Content-Type:application/json

{
"name": "suresh",
"password":"sdfgghdrhd"
}

###

POST http://localhost:5000/login
Content-Type:application/json

{
"name": "suresh",
"password":"sdfgghdrhd"
}